// <auto-generated />
using System;
using ControleDeConta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeConta.Migrations
{
    [DbContext(typeof(ControleDeContasContext))]
    [Migration("20250808033603_Comecando")]
    partial class Comecando
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleDeConta.Modelos.Devedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devedores");
                });

            modelBuilder.Entity("ControleDeConta.Modelos.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("dataDeInicio")
                        .HasColumnType("date");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("devedorId")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("devedorId");

                    b.ToTable("Dividas");
                });

            modelBuilder.Entity("ControleDeConta.Modelos.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.Property<int>("devedorId")
                        .HasColumnType("int");

                    b.Property<int>("dividaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("devedorId");

                    b.HasIndex("dividaId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("ControleDeConta.Modelos.Divida", b =>
                {
                    b.HasOne("ControleDeConta.Modelos.Devedor", "devedor")
                        .WithMany("dividas")
                        .HasForeignKey("devedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("devedor");
                });

            modelBuilder.Entity("ControleDeConta.Modelos.Pagamento", b =>
                {
                    b.HasOne("ControleDeConta.Modelos.Devedor", "devedor")
                        .WithMany("pagamentos")
                        .HasForeignKey("devedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleDeConta.Modelos.Divida", "divida")
                        .WithMany("pagamentos")
                        .HasForeignKey("dividaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("devedor");

                    b.Navigation("divida");
                });

            modelBuilder.Entity("ControleDeConta.Modelos.Devedor", b =>
                {
                    b.Navigation("dividas");

                    b.Navigation("pagamentos");
                });

            modelBuilder.Entity("ControleDeConta.Modelos.Divida", b =>
                {
                    b.Navigation("pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
